version: '3.9'
name: quizza

services:
  quizza-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - .docker.env
    ports:
      - "1433:1433"
    volumes:
      - quizza-sql:/var/opt/mssql
  

  quizza.users.webapi:
    image: ${DOCKER_REGISTRY-}quizzauserswebapi
    environment:
      - ENVIRONMENT_OVERRIDE=Docker
    build:
      context: .
      dockerfile: Quizza.Users.WebApi/Dockerfile


volumes:
  quizza-sql:
  
networks:
  default:
    name: quizza  
